Add Graphlient::Errors::ConnectionFailedError
This is essentially https://github.com/ashkan18/graphlient/pull/59 with test
and some other dependency updates.

Whenever there is an `Errno::ECONNREFUSED` error, Faraday wraps it in a
`Faraday::ConnectionFailed` error. Since it inherits `Faraday::ClientError`
without a response (see errors/faraday_server_error.rb), the code would return
a `NoMethodError: undefined method `[]' for nil:NilClass` error.

So basically the fix is to `rescue Faraday::ConnectionFailed` before rescuing
`Faraday::ClientError` so that we can raise a more meaningful error.

Some other updates:
- Updating ruby to 2.6.5 because zeitwerk requires Ruby version >= 2.4.4.
- I added pry as a dev dependency because I think it's more useful than byebug.
  I can take it out if anyone disagree.
- Minor rubocop fixes.